ARG BASE
FROM ${BASE} AS chrome-base
LABEL authors="appearin"

USER root

COPY google-chrome-stable.etag /tmp/google-chrome-stable.etag
RUN wget --no-verbose -O /tmp/google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
  && apt-get update -qqy \
  && apt-get -qqy install /tmp/google-chrome.deb \
  && dpkg --purge google-chrome-stable \
  && rm -rf /var/lib/apt/lists/* /var/cache/apt/* /tmp/google-chrome.deb /opt/selenium/chromedriver \
  && ln -fs /opt/selenium/chromedriver /usr/bin/chromedriver

USER seluser
COPY generate_config /opt/bin/generate_config
COPY wrap_chrome_binary /opt/bin/wrap_chrome_binary
COPY fetch_chrome /opt/bin/fetch_chrome

USER root

# == Stable
FROM chrome-base as google-chrome-stable
COPY google-chrome-stable.etag /tmp/google-chrome.etag
RUN /opt/bin/fetch_chrome stable
USER seluser
RUN /opt/bin/generate_config > /opt/selenium/config.json
RUN /usr/bin/google-chrome -version

# == Beta
FROM chrome-base as google-chrome-beta
COPY google-chrome-beta.etag /tmp/google-chrome.etag
RUN /opt/bin/fetch_chrome beta
USER seluser
RUN /opt/bin/generate_config > /opt/selenium/config.json
RUN /usr/bin/google-chrome -version

# == Unstable
FROM chrome-base as google-chrome-unstable
COPY google-chrome-unstable.etag /tmp/google-chrome.etag
RUN /opt/bin/fetch_chrome unstable
USER seluser
RUN /opt/bin/generate_config > /opt/selenium/config.json
RUN /usr/bin/google-chrome -version


